-- USANDO O BANCO DE DADOS MERCADO
USE mercado;

-- RESETANDO MAIS FÁCIL AS FUNÇÕES
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM item_venda;
DELETE FROM venda;
DELETE FROM produtos;
DELETE FROM clientes;

ALTER TABLE clientes AUTO_INCREMENT = 1;
ALTER TABLE produtos AUTO_INCREMENT = 1;
ALTER TABLE venda AUTO_INCREMENT = 1;
ALTER TABLE item_venda AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;